apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
specs:
  replicas: 1
  selector:
    matchlabels:
      app: nginx
  template:
    matadata:
      labels:
        apps: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        -containerPort: 80